# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-10 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_osc', models.CharField(max_length=100)),
                ('fecha_solicitud', models.DateTimeField()),
                ('descripcion_caso', models.TextField()),
                ('email_osc', models.EmailField(max_length=254)),
                ('sitio_web_osc', models.URLField()),
                ('tel_oficina_osc', models.CharField(max_length=100)),
                ('direccion_osc', models.CharField(max_length=100)),
                ('codigo_postal_osc', models.CharField(max_length=5)),
                ('razon_social_osc', models.CharField(max_length=100)),
                ('rfc_organizacion', models.CharField(max_length=100)),
                ('direccion_legal_osc', models.CharField(max_length=100)),
                ('descripcion_organizacion', models.CharField(max_length=100)),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('puesto_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=100)),
                ('celular_contacto', models.CharField(max_length=100)),
                ('problema_social_proyecto', models.TextField()),
                ('impacto_proyecto', models.TextField()),
                ('cuenta_con_apoyo', models.CharField(max_length=5)),
                ('fin_religioso', models.CharField(max_length=5)),
                ('tiene_discriminacion', models.CharField(max_length=5)),
                ('miembro_red_probono', models.CharField(max_length=5)),
                ('comienzo_organizacion', models.TextField()),
                ('presupuesto_anual', models.IntegerField()),
                ('fuentes_financiamiento', models.TextField()),
                ('otra_red_abogados', models.CharField(max_length=5)),
                ('recibio_ayuda_probono', models.CharField(max_length=5)),
                ('personal_contratado', models.IntegerField()),
                ('voluntarios_osc', models.IntegerField()),
                ('organos_gobierno', models.TextField()),
                ('cuenta_consejo_independiente', models.CharField(max_length=5)),
                ('presidente_organizacion', models.CharField(max_length=100)),
                ('consejeros_organizacion', models.CharField(max_length=100)),
                ('beneficiarios_directos', models.TextField()),
                ('beneficiarios_indirectos', models.TextField()),
                ('caracteristicas_comunidad', models.TextField()),
                ('porque_quiere_fortalecer', models.TextField()),
                ('cuenta_aviso_privacidad', models.CharField(max_length=5)),
                ('sabe_fechas_avisos_antilavado', models.CharField(max_length=5)),
                ('sabe_fecha_entrega_declaracion_anual', models.CharField(max_length=5)),
                ('acta_constitutiva', models.BooleanField(default=False)),
                ('recibos_sat', models.BooleanField(default=False)),
                ('cluni', models.BooleanField(default=False)),
                ('relatorio_anual', models.BooleanField(default=False)),
                ('reporte_logros', models.BooleanField(default=False)),
                ('auditoria_anual', models.BooleanField(default=False)),
                ('comentarios_adicionales', models.TextField(null=True)),
                ('acuerdo_entrega_docs', models.CharField(max_length=5)),
                ('terminos_condiciones', models.CharField(max_length=5)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conocimiento_redprobono_mexico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osc_ciudad', to='catalogos.ConocimientoRedProbono')),
                ('estado_clearing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_clearing', to='catalogos.EstadoClearing')),
                ('localidad_osc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osc_localidad', to='catalogos.Localidades')),
                ('materias_enfoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osc_ciudad', to='catalogos.Materias')),
                ('materias_legales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osc_ciudad', to='catalogos.Legales')),
                ('pais_osc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osc_pais', to='catalogos.Paises')),
                ('provincia_osc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osc_ciudad', to='catalogos.Ciudades')),
                ('subestado_clearing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_clearing', to='catalogos.SubEstadosClearing')),
                ('tipo_comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osc_ciudad', to='catalogos.Comunidades')),
            ],
        ),
    ]
