# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-11 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_auto_20180911_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadesProbono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
    ]
